export const feedData: any[] = [
  {
    logo: 'L',
    name: 'Luffy',
    content: 'Kaizoku ou ni ore wa naru',
    img: '../../../assets/images/luffy.jpg',
    upvoteCount: 200,
    commentCount: 2,
    comment: [
      {
        logo: 'L',
        topic: 'Luffy',
        body: 'I will Help You',
        upvote: 150,
      },
      {
        logo: 'S',
        topic: 'Sanji',
        body: 'Yeah, Right',
        upvote: 150,
      },
    ],
  },
  
  {
    logo: 'Z',
    name: 'Zoro',
    content: 'Scars on the back are a swordsman shame',
    img: '../../../assets/images/zoro.jpg',
    upvoteCount: 300,
    commentCount: 3,
  },
  {
    logo: 'N',
    name: 'Naruto',
    content: 'Watashi wa hokage ni naru',
    img: '../../../assets/images/naruto.jpg',
    upvoteCount: 400,
    commentCount: 2,
  },
  {
    logo: 'M',
    name: 'Maskman',
    content: 'No one cared until I started wearing mask',
    img: '../../../assets/images/pexels-photo-1097456 (1).jpg',
    upvoteCount: 300,
    commentCount: 2,
  },
  {
    logo: 'M',
    name: 'ManchesterUnited',
    content: 'Manchester United #ggmu',
    img: '../../../assets/images/man.jpg',
    upvoteCount: 700,
    commentCount: 2,
  },
  {
    logo: 'O',
    name: 'OnePiece',
    content: 'The One Piece is Real',
    img: '../../../assets/images/onepiece.jpeg',
    upvoteCount: 800,
    commentCount: 2,
  },
  {
    logo: 'B',
    name: 'BatMan',
    content: 'The World only make sense, If you force it to',
    img: '../../../assets/images/bat.jpg',
    upvoteCount: 900,
    commentCount: 2,
  },
];