import { FeedData } from "../models/feed-data";

export const FEED_DATA: FeedData[] = [
  {
    id: 0,
    logo: 'L',
    name: 'Luffy',
    content: 'Kaizoku ou ni ore wa naru',
    img: '../../../assets/images/luffy.jpg',
    upvoteCount: 200,
    commentCount: 2,
    comment: [
      {
        logo: 'L',
        title: 'Luffy',
        body: 'I will Help You',
        upvote: 150,
      },
      {
        logo: 'S',
        title: 'Sanji',
        body: 'Yeah, Right',
        upvote: 150,
      },
    ],
  },

  {
    id: 11,
    logo: 'Z',
    name: 'Zoro',
    content: 'Scars on the back are a swordsman shame',
    img: '../../../assets/images/zoro.jpg',
    upvoteCount: 300,
    commentCount: 2,
    comment: [
      {
        logo: 'L',
        title: 'Luffy',
        body: 'I will Help You',
        upvote: 150,
      },
      {
        logo: 'S',
        title: 'Sanji',
        body: 'Yeah, Right',
        upvote: 150,
      },
    ],
  },
  {
    id: 2,
    logo: 'N',
    name: 'Naruto',
    content: 'Watashi wa hokage ni naru',
    img: '../../../assets/images/naruto.jpg',
    upvoteCount: 400,
    commentCount: 2,
    comment: [
      {
        logo: 'S',
        title: 'Sasuke',
        body: 'Naruto',
        upvote: 150,
      },
      {
        logo: 'H',
        title: 'Hinata',
        body: 'Naruto Kun',
        upvote: 800,
      },
    ],
  },
  {
    id: 3,
    logo: 'M',
    name: 'Maskman',
    content: 'No one cared until I started wearing mask',
    img: '../../../assets/images/mask.jpg',
    upvoteCount: 300,
    commentCount: 0,
    comment: [],
  },
  {
    id: 4,
    logo: 'M',
    name: 'ManchesterUnited',
    content: 'Manchester United #ggmu',
    img: '../../../assets/images/man.jpg',
    upvoteCount: 700,
    commentCount: 0,
    comment: [],
  },
  {
    id: 5,
    logo: 'O',
    name: 'OnePiece',
    content: 'The One Piece is Real',
    img: '../../../assets/images/onepiece.jpeg',
    upvoteCount: 800,
    commentCount: 0,
    comment: [],
  },
  {
    id: 6,
    logo: 'B',
    name: 'BatMan',
    content: 'The World only make sense, If you force it to',
    img: '../../../assets/images/bat.jpg',
    upvoteCount: 900,
    commentCount: 1,
    comment: [
      {
        logo: 'B',
        title: 'Batman Forever',
        body: 'I am Vengence, I am the Knight, I am Batman',
        upvote: 800,
      },
    ],
  },
];